on:
  workflow_call:

jobs:
  validate_branch_job:
    runs-on: ubuntu-latest
    name: Branch checks job
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: thalluripk/github-actions/branch-policy@main
