on:
  workflow_call:
    inputs:
      branch-name:
        type: string
        required: true
        description: enter user name

jobs:
  validate_branch_job:
    runs-on: ubuntu-latest
    name: Branch checks job
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: thalluripk/github-actions/branch-policy@main
        with:
          branch-name: ${{inputs.branch-name}}
      - run: write-output "random-number ${{ steps.foo.outputs.random-number }}"
        shell: pwsh
