on:
  workflow_call:
    inputs:
      user:
        type: string
        required: true
        description: enter user name

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: thalluripk/github-actions/branch-policy@main
        with:
          who-to-greet: ${{inputs.user}}
      - run: write-output "random-number ${{ steps.foo.outputs.random-number }}"
        shell: pwsh
